name: tests core 10

on:
  push:
    branch:
      - "1"

# Really GitHub ? We need to keep this outdated workflow file, so we can have available to select in
# the action pane - and furthermore to show a corresponing badge. Even if core v10 test are only done
# on split-branches.

jobs:
  testsuite:
    name: all tests with core 10
    runs-on: ubuntu-20.04
    steps:
      - name: dummy
        run: echo 'disabled on branches not supporting this anymore'

